### PR TITLE
Empty state / only allowing specific widgets

### PR DESCRIPTION
**Pull request by wannesmatthys**
Awesome plugin! Some clients have been asking this to us for quite some time, so I made some slight changes so we can start using this soon! :) 

This PR has the following functionality:

1) Setting an empty state when no widgets are set

2) Only allowing specific widgets to be selected by the user

3) Set some basic functions on the page (shouldRegisterNavigation, navigationSort and navigationGroup).

### CODE REVIEW

**Comment by invaders-xx** [comment]
Hi, I will not merge this PR 
1) as the second point can/has to be handled by the function filterVisibleWidgets and auth access to a Widget has to be handled within the widget.
2) Regarding first point, this has to be handled using a function within the plugin and not in the config file
Regarding point 3) I agree that some basic functions can be added,

**Comment by wannesmatthys** [comment]
> Hi, I will not merge this PR
> 
> 1. as the second point can/has to be handled by the function filterVisibleWidgets and auth access to a Widget has to be handled within the widget.
> 2. Regarding first point, this has to be handled using a function within the plugin and not in the config file
>    Regarding point 3) I agree that some basic functions can be added,

Hi, thanks for the response, all valid points. 
Didn't know `filterVisibleWidgets`existed, so I'll remove that. If I rework the emptyState stuff using a function, are you considering a merge? Than I'll have a look at this tmrw.

Thanks!

**Comment by invaders-xx** [comment]
filterVisibleWidgets already filters widgets based on the widget's canView function. So you only have to manage the access within each plugin in the function canView, no need to add anything in this plugin for that

**Comment by invaders-xx** [comment]
regarding other points I will handle that myself tomorrow morning

**Comment by invaders-xx** [comment]
New version with defaultGrid, navigationIcon, navigationGroup and navigationSort. You will have to deal with your point 2 by yourself using canView in each widget

**Pull request closed without merging**
